version: 2.1
workflows:
  my_workflow:
    jobs:
      - tests:
          context: postnauka_nm
jobs:
  tests:
    docker:
      - image: circleci/openjdk:8u265-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: "echo environment variables from postnauka_nm context"
          command: echo $MY_ENV_VAR
      # run tests!
      - run:
          name: Get chrome version
          command: google-chrome --version
      - run:
          name: Running tests
          command: mvn clean install
      - run:
          name: Generate allure report
          command: mvn allure:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
          when: always
      - store_artifacts:
          path: target/site/allure-maven-plugin/